-module(af_hos_stress_tests).

-include_lib("eunit/include/eunit.hrl").
-include("token.hrl").
-include("continuation.hrl").

%% Concurrent stress harness for the HOS elevator.
%%
%% N floor-button-press events interleaved with random fire-alarm
%% and fire-clear toggles over a sustained run. Verifies that the
%% invariants implied by the correctness argument
%% (mailbox serialization + Axiom 4 input rejection + exhaustive
%% emergency coverage) hold under every observed interleaving.
%%
%% This is not property-based testing. A dedicated PBT harness
%% (QuickCheck / PropEr) is deliberately skipped for v1 per the
%% roadmap (expensive, marginal talk-value). The test here
%% exercises a concrete stream of interleaved events chosen to
%% cover the combinations that would reveal a hole: emergency
%% during travel, emergency during loading, emergency during door
%% open, back-to-back emergencies, and clears between emergencies.
%%
%% If the mailbox + Axiom 4 + exhaustive emergencies combination
%% has a hole, a sustained run will either crash a process
%% (undeclared transition reached), leave a process stuck
%% (waiting for a signal that never fires), or produce a log
%% containing tokens that cannot be justified from the spec. Each
%% invariant below checks one of these.

setup() ->
    af_repl:init_types(),
    af_type_compiler:clear_pending_checks(),
    af_hos_check:clear_registry().

load_valid_spec() ->
    {ok, Content} = file:read_file(
        "samples/hos/elevator/elevator.a4"),
    Tokens = af_parser:parse(binary_to_list(Content), "stress"),
    af_interpreter:interpret_tokens(
        Tokens, af_interpreter:new_continuation()).

get_log(Pid) ->
    Ref = make_ref(),
    Pid ! {get_log, self(), Ref},
    receive
        {reply, Ref, Log} -> Log
    after 2000 ->
        {error, timeout}
    end.

introspect_child_pid(ParentPid, ChildName) ->
    Ref = make_ref(),
    ParentPid ! {introspect_child, ChildName, self(), Ref},
    receive
        {reply, Ref, Pid} -> Pid
    after 2000 ->
        {error, timeout}
    end.


%% -------------------------------------------------------------------
%% The stress run.
%% -------------------------------------------------------------------

stress_test_() ->
    {foreach, fun setup/0, fun(_) -> ok end, [
        fun(_) -> {"20 events with emergency toggles, seed A",
            {timeout, 30, fun() ->
                run_stress_scenario({7, 11, 13}, 20)
            end}} end,

        fun(_) -> {"20 events with emergency toggles, seed B",
            {timeout, 30, fun() ->
                run_stress_scenario({101, 202, 303}, 20)
            end}} end,

        fun(_) -> {"40 events with emergency toggles, seed C",
            {timeout, 60, fun() ->
                run_stress_scenario({42, 42, 42}, 40)
            end}} end
     ]}.

run_stress_scenario(Seed, NEvents) ->
    load_valid_spec(),
    Root = af_hos_check:lookup_system("BuildingSystem"),
    RootPid = af_hos_runtime:spawn_system(Root),
    DispPid  = introspect_child_pid(RootPid,  "Dispatcher"),
    CarPid   = introspect_child_pid(DispPid, "Car"),
    DoorPid  = introspect_child_pid(CarPid,  "Door"),
    MotorPid = introspect_child_pid(CarPid,  "Motor"),

    %% Deterministic interleaving seed so failures are reproducible.
    _ = rand:seed(exsss, Seed),

    ok = drive_events(RootPid, NEvents),

    %% Let any scheduled timers drain. 1500ms covers the longest
    %% outstanding timer chain (Motor 500 + Car settle 200 + Door
    %% open 100 + Car depart 300 + Door close 100 = 1200, with
    %% margin).
    timer:sleep(1500),

    DoorLog  = get_log(DoorPid),
    MotorLog = get_log(MotorPid),
    CarLog   = get_log(CarPid),

    %% Invariant 1: all processes survived. A crashed actor would
    %% have dropped its mailbox.
    ?assert(is_process_alive(RootPid)),
    ?assert(is_process_alive(DispPid)),
    ?assert(is_process_alive(CarPid)),
    ?assert(is_process_alive(DoorPid)),
    ?assert(is_process_alive(MotorPid)),

    %% Invariant 2: logs contain only declared-event tokens. An
    %% undeclared token would mean the runtime received a message
    %% that should be impossible to construct.
    ?assert(log_tokens_subset_of(DoorLog,
        ["close", "closed", "open", "opened"])),
    ?assert(log_tokens_subset_of(MotorLog,
        ["move-to", "arrived", "stop"])),
    ?assert(log_tokens_subset_of(CarLog,
        ["assign", "closed", "opened", "arrived", "settled",
         "depart", "trigger-emergency", "clear-emergency"])),

    %% Invariant 3: activity happened. A stuck tree would have empty
    %% child logs.
    ?assert(length(DoorLog)  > 0),
    ?assert(length(MotorLog) > 0),

    %% Invariant 4: every "arrived" in Motor log is preceded by at
    %% least one "move-to". The scheduled arrived self-send is only
    %% generated by a move-to transition.
    ?assert(count_preceded_by("arrived", "move-to", MotorLog)),

    %% Invariant 5: every "opened" / "closed" in Door log is
    %% preceded by at least one "open" / "close" respectively. The
    %% scheduled opened / closed self-sends are only generated by
    %% Opening / Closing transitions.
    ?assert(count_preceded_by("opened", "open",  DoorLog)),
    ?assert(count_preceded_by("closed", "close", DoorLog)),

    af_hos_runtime:stop_system(RootPid),
    timer:sleep(100).


%% -------------------------------------------------------------------
%% Event driver.
%% -------------------------------------------------------------------
%%
%% drive_events/2 emits N events in sequence with a small delay
%% between each. A fraction of the events are emergency-related
%% (fire-alarm / fire-clear), balanced against floor-button-press.
%% The intention is to hit every interesting interleaving: emergency
%% during assign, clear during travel, back-to-back emergencies,
%% emergency while in loading state, etc.
drive_events(_Root, 0) -> ok;
drive_events(Root, N) ->
    Pick = rand:uniform(100),
    Event =
        if
            Pick =< 55 -> 'floor-button-press';
            Pick =< 80 -> 'fire-alarm';
            true       -> 'fire-clear'
        end,
    af_hos_runtime:send_event(Root, Event, []),
    %% Sleep a short random duration (20 to 250ms). This is wide
    %% enough to hit different Car states for emergency injection.
    timer:sleep(20 + rand:uniform(230)),
    drive_events(Root, N - 1).


%% -------------------------------------------------------------------
%% Invariant helpers.
%% -------------------------------------------------------------------

log_tokens_subset_of(Log, Allowed) ->
    lists:all(fun(Tok) -> lists:member(Tok, Allowed) end, Log).

%% Every occurrence of Event in Log has at least one Prerequisite
%% earlier in Log. Cumulative check: for each position where Event
%% appears, the prefix up to that position must already contain
%% Prerequisite.
count_preceded_by(Event, Prereq, Log) ->
    count_preceded_by(Event, Prereq, Log, 0, 0).

count_preceded_by(_Event, _Prereq, [], _, _) ->
    true;
count_preceded_by(Event, Prereq, [Event | Rest], EventsSeen, PrereqsSeen)
        when PrereqsSeen > EventsSeen ->
    count_preceded_by(Event, Prereq, Rest, EventsSeen + 1, PrereqsSeen);
count_preceded_by(Event, _Prereq, [Event | _], _, _) ->
    false;
count_preceded_by(Event, Prereq, [Prereq | Rest], EventsSeen, PrereqsSeen) ->
    count_preceded_by(Event, Prereq, Rest, EventsSeen, PrereqsSeen + 1);
count_preceded_by(Event, Prereq, [_Other | Rest], EventsSeen, PrereqsSeen) ->
    count_preceded_by(Event, Prereq, Rest, EventsSeen, PrereqsSeen).
