-module(af_cpp_compiler).

-include("token.hrl").
-include("operation.hrl").
-include("continuation.hrl").
-include("af_type.hrl").

-export([init/0]).
-export([compile_to_cpp/2, compile_file_to_cpp/2]).
-export([generate_cpp/2]).
-export([find_all_compiled_words/0, find_all_product_types/0]).

%% Initialize the compile-to-cpp word in the Any dictionary.
init() ->
    af_type:add_op('Any', #operation{
        name = "compile-to-cpp",
        sig_in = ['String', 'String'],
        sig_out = [],
        impl = fun op_compile_to_cpp/1
    }),
    ok.

%% ActorForth word: compile-to-cpp
%% ( output_path module_name -- )
%% Interprets current word definitions and generates C++ source file.
op_compile_to_cpp(Cont) ->
    [{'String', ModNameBin}, {'String', PathBin} | Rest] = Cont#continuation.data_stack,
    ModName = binary_to_list(ModNameBin),
    Path = binary_to_list(PathBin),
    WordDefs = find_all_compiled_words(),
    ProductTypes = find_all_product_types(),
    CppCode = generate_cpp(ModName, #{words => WordDefs, types => ProductTypes}),
    ok = file:write_file(Path, CppCode),
    Cont#continuation{data_stack = Rest}.

%% Compile an .a4 file to C++ source.
compile_file_to_cpp(A4Path, CppPath) ->
    {ok, Content} = file:read_file(A4Path),
    af_repl:init_types(),
    init(),
    C = af_interpreter:new_continuation(),
    Tokens = af_parser:parse(binary_to_list(Content), A4Path),
    af_interpreter:interpret_tokens(Tokens, C),
    WordDefs = find_all_compiled_words(),
    ProductTypes = find_all_product_types(),
    ModName = filename:rootname(filename:basename(A4Path)),
    CppCode = generate_cpp(ModName, #{words => WordDefs, types => ProductTypes}),
    ok = file:write_file(CppPath, CppCode),
    {ok, CppPath}.

%% Compile word definitions to C++ from the interpreter state.
compile_to_cpp(ModName, CppPath) ->
    WordDefs = find_all_compiled_words(),
    ProductTypes = find_all_product_types(),
    CppCode = generate_cpp(ModName, #{words => WordDefs, types => ProductTypes}),
    ok = file:write_file(CppPath, CppCode),
    {ok, CppPath}.

%%% ===================================================================
%%% C++ Code Generation
%%% ===================================================================

generate_cpp(ModName, #{words := WordDefs, types := ProductTypes}) ->
    Header = generate_header(ModName),
    TypeDefs = generate_type_defs(ProductTypes),
    {FwdDecls, FunDefs} = generate_functions(WordDefs),
    Main = generate_main(ModName),
    iolist_to_binary([
        Header, "\n",
        TypeDefs, "\n",
        FwdDecls, "\n",
        FunDefs, "\n",
        Main
    ]).

generate_header(ModName) ->
    [
        "// Generated by ActorForth C++ compiler\n",
        "// Module: ", ModName, "\n",
        "//\n",
        "// This file was auto-generated from ActorForth source.\n",
        "// Do not edit manually.\n\n",
        "#include <algorithm>\n",
        "#include <cstdint>\n",
        "#include <cmath>\n",
        "#include <string>\n",
        "#include <vector>\n",
        "#include <variant>\n",
        "#include <stdexcept>\n",
        "#include <iostream>\n",
        "#include <functional>\n",
        "#include <cassert>\n\n",
        "namespace af {\n\n",
        generate_value_type(),
        "\n"
    ].

generate_value_type() ->
    [
        "// Tagged value type -- mirrors ActorForth's {Type, Value} stack items\n",
        "enum class Type {\n",
        "    Int, Float, Bool, String, Atom, List, Map, Tuple, Actor, Product\n",
        "};\n\n",
        "struct Value;\n",
        "using Stack = std::vector<Value>;\n",
        "using ProductFields = std::vector<std::pair<std::string, Value>>;\n\n",
        "struct Value {\n",
        "    Type type;\n",
        "    std::variant<\n",
        "        int64_t,           // Int\n",
        "        double,            // Float\n",
        "        bool,              // Bool\n",
        "        std::string,       // String, Atom\n",
        "        std::vector<Value>,// List\n",
        "        ProductFields      // Product type fields\n",
        "    > data;\n",
        "    std::string type_name; // For product types: the type name\n\n",
        "    // Constructors\n",
        "    static Value make_int(int64_t v) { return {Type::Int, v, \"\"}; }\n",
        "    static Value make_float(double v) { return {Type::Float, v, \"\"}; }\n",
        "    static Value make_bool(bool v) { return {Type::Bool, v, \"\"}; }\n",
        "    static Value make_string(const std::string& v) { return {Type::String, v, \"\"}; }\n",
        "    static Value make_atom(const std::string& v) { return {Type::Atom, v, \"\"}; }\n",
        "    static Value make_list(const std::vector<Value>& v) { return {Type::List, v, \"\"}; }\n",
        "    static Value make_product(const std::string& name, const ProductFields& fields) {\n",
        "        return {Type::Product, fields, name};\n",
        "    }\n\n",
        "    // Accessors\n",
        "    int64_t as_int() const { return std::get<int64_t>(data); }\n",
        "    double as_float() const { return std::get<double>(data); }\n",
        "    bool as_bool() const { return std::get<bool>(data); }\n",
        "    const std::string& as_string() const { return std::get<std::string>(data); }\n",
        "    const std::vector<Value>& as_list() const { return std::get<std::vector<Value>>(data); }\n",
        "    const ProductFields& as_fields() const { return std::get<ProductFields>(data); }\n",
        "    ProductFields& as_fields_mut() { return std::get<ProductFields>(data); }\n\n",
        "    // Field access for product types\n",
        "    const Value& field(const std::string& name) const {\n",
        "        for (auto& [k, v] : as_fields()) if (k == name) return v;\n",
        "        throw std::runtime_error(\"Unknown field: \" + name);\n",
        "    }\n",
        "    Value with_field(const std::string& name, const Value& val) const {\n",
        "        auto fields = as_fields();\n",
        "        for (auto& [k, v] : fields) if (k == name) { v = val; break; }\n",
        "        return make_product(type_name, fields);\n",
        "    }\n\n",
        "    // Equality\n",
        "    bool operator==(const Value& other) const {\n",
        "        return type == other.type && data == other.data;\n",
        "    }\n",
        "    bool operator!=(const Value& other) const { return !(*this == other); }\n",
        "};\n\n",
        "// Stack operations\n",
        "inline Value pop(Stack& s) {\n",
        "    auto v = std::move(s.back()); s.pop_back(); return v;\n",
        "}\n",
        "inline void push(Stack& s, Value v) { s.push_back(std::move(v)); }\n",
        "inline const Value& peek(const Stack& s) { return s.back(); }\n\n"
    ].

%%% ===================================================================
%%% Product Type Generation
%%% ===================================================================

generate_type_defs([]) -> [];
generate_type_defs(ProductTypes) ->
    [
        "// Product type constructors and accessors\n\n",
        [generate_product_type(T) || T <- ProductTypes]
    ].

generate_product_type({TypeName, Fields}) ->
    NameStr = atom_to_list(TypeName),
    ConstructorName = string:lowercase(NameStr),
    [
        "// Product type: ", NameStr, "\n",
        "inline Value make_", ConstructorName, "(", generate_constructor_params(Fields), ") {\n",
        "    ProductFields fields = {\n",
        generate_field_inits(Fields),
        "    };\n",
        "    return Value::make_product(\"", NameStr, "\", fields);\n",
        "}\n\n",
        %% Stack-based constructor (pops N values, pushes product)
        generate_stack_constructor(NameStr, ConstructorName, Fields),
        %% Getter functions
        [generate_getter(NameStr, FName, FType) || {FName, FType} <- Fields],
        %% Setter functions
        [generate_setter(NameStr, FName, FType) || {FName, FType} <- Fields],
        "\n"
    ].

generate_stack_constructor(TypeName, ConstructorName, Fields) ->
    %% Pop fields in reverse order (TOS = last field), construct product, push
    RevFields = lists:reverse(Fields),
    PopVars = [["    auto ", atom_to_list(FName), "_val = pop(s);\n"]
               || {FName, _FType} <- RevFields],
    FieldPairs = [["        {\"", atom_to_list(FName), "\", ", atom_to_list(FName), "_val}"]
                  || {FName, _FType} <- Fields],
    [
        "// Stack-based constructor: pops ", integer_to_list(length(Fields)),
        " values, pushes ", TypeName, "\n",
        "inline void make_", ConstructorName, "_push(Stack& s) {\n",
        PopVars,
        "    ProductFields fields = {\n",
        lists:join(",\n", FieldPairs), "\n",
        "    };\n",
        "    push(s, Value::make_product(\"", TypeName, "\", fields));\n",
        "}\n\n"
    ].

generate_constructor_params(Fields) ->
    Params = [generate_param(FName, FType) || {FName, FType} <- Fields],
    lists:join(", ", Params).

generate_param(FName, FType) ->
    [cpp_param_type(FType), " ", atom_to_list(FName)].

generate_field_inits(Fields) ->
    Inits = [["        {\"", atom_to_list(FName), "\", ",
              cpp_make_value(FType, atom_to_list(FName)), "}"]
             || {FName, FType} <- Fields],
    lists:join(",\n", Inits) ++ "\n".

generate_getter(TypeName, FName, _FType) ->
    FNameStr = atom_to_list(FName),
    [
        "// ", TypeName, ".", FNameStr, " (non-destructive getter)\n",
        "inline void op_", string:lowercase(TypeName), "_", FNameStr, "(Stack& s) {\n",
        "    auto& instance = s.back();\n",
        "    push(s, instance.field(\"", FNameStr, "\"));\n",
        "}\n\n"
    ].

generate_setter(TypeName, FName, _FType) ->
    FNameStr = atom_to_list(FName),
    [
        "// ", TypeName, ".", FNameStr, "! (setter)\n",
        "inline void op_", string:lowercase(TypeName), "_", FNameStr, "_set(Stack& s) {\n",
        "    auto new_val = pop(s);\n",
        "    auto instance = pop(s);\n",
        "    push(s, instance.with_field(\"", FNameStr, "\", new_val));\n",
        "}\n\n"
    ].

%%% ===================================================================
%%% Function Generation
%%% ===================================================================

generate_functions(WordDefs) ->
    Grouped = group_by_name(WordDefs),
    FwdDecls = ["// Forward declarations\n",
                [generate_fwd_decl(Name) || {Name, _} <- Grouped],
                "\n"],
    FunDefs = [generate_word_group(Name, Defs) || {Name, Defs} <- Grouped],
    {FwdDecls, FunDefs}.

generate_fwd_decl(Name) ->
    CppName = cpp_function_name(Name),
    ["void ", CppName, "(Stack& s);\n"].

generate_word_group(Name, Defs) ->
    CppName = cpp_function_name(Name),
    case Defs of
        [SingleDef] ->
            generate_single_function(CppName, Name, SingleDef);
        MultipleDefs ->
            generate_multi_clause_function(CppName, Name, MultipleDefs)
    end.

generate_single_function(CppName, Name, {_Name, SigIn, _SigOut, Body}) ->
    BodyCode = generate_body(Body, SigIn, Name),
    [
        "// Word: ", Name, "\n",
        "// Signature: ", format_sig(SigIn), " -> ", format_sig(_SigOut), "\n",
        "void ", CppName, "(Stack& s) {\n",
        BodyCode,
        "}\n\n"
    ].

generate_multi_clause_function(CppName, Name, Defs) ->
    %% Value-constrained clauses first, general clause last
    {Constrained, General} = lists:partition(fun({_, SigIn, _, _}) ->
        lists:any(fun(S) -> is_tuple(S) end, SigIn)
    end, Defs),
    Clauses = Constrained ++ General,
    [
        "// Word: ", Name, " (multi-clause)\n",
        "void ", CppName, "(Stack& s) {\n",
        generate_clauses(Clauses, Name, true),
        "}\n\n"
    ].

generate_clauses([], _Name, _First) -> [];
generate_clauses([{_, SigIn, _SigOut, Body} | Rest], Name, First) ->
    HasConstraint = lists:any(fun(S) -> is_tuple(S) end, SigIn),
    case HasConstraint of
        true ->
            Cond = generate_match_condition(SigIn),
            Keyword = case First of true -> "if"; false -> "} else if" end,
            [
                "    ", Keyword, " (", Cond, ") {\n",
                generate_body(Body, SigIn, Name),
                generate_clauses(Rest, Name, false)
            ];
        false ->
            case First of
                true ->
                    [
                        generate_body(Body, SigIn, Name),
                        generate_clauses(Rest, Name, false)
                    ];
                false ->
                    [
                        "    } else {\n",
                        generate_body(Body, SigIn, Name),
                        "    }\n",
                        generate_clauses(Rest, Name, false)
                    ]
            end
    end.

generate_match_condition(SigIn) ->
    %% Generate condition checking value constraints
    %% SigIn is TOS-first, so index 0 = back of vector
    Conditions = lists:filtermap(fun({Idx, SigEntry}) ->
        case SigEntry of
            {Type, Value} ->
                StackIdx = io_lib:format("s[s.size() - ~B]", [Idx]),
                {true, [StackIdx, " == ", cpp_literal_value(Type, Value)]};
            _ -> false
        end
    end, lists:zip(lists:seq(1, length(SigIn)), SigIn)),
    lists:join(" && ", Conditions).

%%% ===================================================================
%%% Body Code Generation
%%% ===================================================================

generate_body(Body, _SigIn, WordName) ->
    Ops = [generate_op(Op, WordName) || Op <- Body],
    Ops.

generate_op(#operation{name = Name}, WordName) ->
    translate_to_cpp(Name, WordName).

%% Stack operations
translate_to_cpp("dup", _) ->
    "    push(s, peek(s));\n";
translate_to_cpp("drop", _) ->
    "    pop(s);\n";
translate_to_cpp("swap", _) ->
    [
        "    { auto a = pop(s); auto b = pop(s);\n",
        "      push(s, std::move(a)); push(s, std::move(b)); }\n"
    ];
translate_to_cpp("rot", _) ->
    %% a b c rot → b c a  (move 3rd-from-top to TOS)
    [
        "    { auto c = pop(s); auto b = pop(s); auto a = pop(s);\n",
        "      push(s, std::move(b)); push(s, std::move(c)); push(s, std::move(a)); }\n"
    ];
translate_to_cpp("over", _) ->
    "    push(s, s[s.size() - 2]);\n";
translate_to_cpp("2dup", _) ->
    [
        "    { auto a = s[s.size() - 1]; auto b = s[s.size() - 2];\n",
        "      push(s, b); push(s, a); }\n"
    ];

%% Arithmetic
translate_to_cpp("+", _) ->
    [
        "    { auto a = pop(s); auto b = pop(s);\n",
        "      push(s, Value::make_int(b.as_int() + a.as_int())); }\n"
    ];
translate_to_cpp("-", _) ->
    [
        "    { auto a = pop(s); auto b = pop(s);\n",
        "      push(s, Value::make_int(b.as_int() - a.as_int())); }\n"
    ];
translate_to_cpp("*", _) ->
    [
        "    { auto a = pop(s); auto b = pop(s);\n",
        "      push(s, Value::make_int(b.as_int() * a.as_int())); }\n"
    ];
translate_to_cpp("/", _) ->
    [
        "    { auto a = pop(s); auto b = pop(s);\n",
        "      if (a.as_int() == 0) throw std::runtime_error(\"Division by zero\");\n",
        "      push(s, Value::make_int(b.as_int() / a.as_int())); }\n"
    ];
translate_to_cpp("mod", _) ->
    [
        "    { auto a = pop(s); auto b = pop(s);\n",
        "      push(s, Value::make_int(b.as_int() % a.as_int())); }\n"
    ];
translate_to_cpp("abs", _) ->
    [
        "    { auto a = pop(s);\n",
        "      push(s, Value::make_int(std::abs(a.as_int()))); }\n"
    ];
translate_to_cpp("max", _) ->
    [
        "    { auto a = pop(s); auto b = pop(s);\n",
        "      push(s, Value::make_int(std::max(b.as_int(), a.as_int()))); }\n"
    ];
translate_to_cpp("min", _) ->
    [
        "    { auto a = pop(s); auto b = pop(s);\n",
        "      push(s, Value::make_int(std::min(b.as_int(), a.as_int()))); }\n"
    ];

%% Comparisons
translate_to_cpp("==", _) ->
    [
        "    { auto a = pop(s); auto b = pop(s);\n",
        "      push(s, Value::make_bool(b == a)); }\n"
    ];
translate_to_cpp("!=", _) ->
    [
        "    { auto a = pop(s); auto b = pop(s);\n",
        "      push(s, Value::make_bool(b != a)); }\n"
    ];
translate_to_cpp("<", _) ->
    [
        "    { auto a = pop(s); auto b = pop(s);\n",
        "      push(s, Value::make_bool(b.as_int() < a.as_int())); }\n"
    ];
translate_to_cpp(">", _) ->
    [
        "    { auto a = pop(s); auto b = pop(s);\n",
        "      push(s, Value::make_bool(b.as_int() > a.as_int())); }\n"
    ];
translate_to_cpp("<=", _) ->
    [
        "    { auto a = pop(s); auto b = pop(s);\n",
        "      push(s, Value::make_bool(b.as_int() <= a.as_int())); }\n"
    ];
translate_to_cpp(">=", _) ->
    [
        "    { auto a = pop(s); auto b = pop(s);\n",
        "      push(s, Value::make_bool(b.as_int() >= a.as_int())); }\n"
    ];

%% Boolean
translate_to_cpp("not", _) ->
    [
        "    { auto a = pop(s);\n",
        "      push(s, Value::make_bool(!a.as_bool())); }\n"
    ];
translate_to_cpp("and", _) ->
    [
        "    { auto a = pop(s); auto b = pop(s);\n",
        "      push(s, Value::make_bool(b.as_bool() && a.as_bool())); }\n"
    ];
translate_to_cpp("or", _) ->
    [
        "    { auto a = pop(s); auto b = pop(s);\n",
        "      push(s, Value::make_bool(b.as_bool() || a.as_bool())); }\n"
    ];

%% String operations
translate_to_cpp("trim", _) ->
    [
        "    { auto a = pop(s);\n",
        "      auto str = a.as_string();\n",
        "      auto start = str.find_first_not_of(\" \\t\\n\\r\");\n",
        "      if (start == std::string::npos) push(s, Value::make_string(\"\"));\n",
        "      else {\n",
        "          auto end = str.find_last_not_of(\" \\t\\n\\r\");\n",
        "          push(s, Value::make_string(str.substr(start, end - start + 1)));\n",
        "      } }\n"
    ];
translate_to_cpp("to-upper", _) ->
    [
        "    { auto a = pop(s);\n",
        "      auto str = a.as_string();\n",
        "      std::transform(str.begin(), str.end(), str.begin(), ::toupper);\n",
        "      push(s, Value::make_string(str)); }\n"
    ];
translate_to_cpp("to-lower", _) ->
    [
        "    { auto a = pop(s);\n",
        "      auto str = a.as_string();\n",
        "      std::transform(str.begin(), str.end(), str.begin(), ::tolower);\n",
        "      push(s, Value::make_string(str)); }\n"
    ];
translate_to_cpp("concat", _) ->
    [
        "    { auto a = pop(s); auto b = pop(s);\n",
        "      push(s, Value::make_string(b.as_string() + a.as_string())); }\n"
    ];
translate_to_cpp("length", _) ->
    %% Works for both String and List
    [
        "    { auto& a = peek(s);\n",
        "      if (a.type == Type::String)\n",
        "          { auto v = pop(s); push(s, Value::make_int(v.as_string().size())); }\n",
        "      else if (a.type == Type::List)\n",
        "          { auto v = pop(s); push(s, Value::make_int(v.as_list().size())); }\n",
        "    }\n"
    ];

%% List operations
translate_to_cpp("nil", _) ->
    "    push(s, Value::make_list({}));\n";
translate_to_cpp("cons", _) ->
    [
        "    { auto item = pop(s); auto lst = pop(s);\n",
        "      auto vec = lst.as_list();\n",
        "      vec.insert(vec.begin(), std::move(item));\n",
        "      push(s, Value::make_list(vec)); }\n"
    ];
translate_to_cpp("head", _) ->
    [
        "    { auto lst = pop(s);\n",
        "      push(s, lst.as_list().front()); }\n"
    ];
translate_to_cpp("tail", _) ->
    [
        "    { auto lst = pop(s);\n",
        "      auto& vec = lst.as_list();\n",
        "      push(s, Value::make_list({vec.begin() + 1, vec.end()})); }\n"
    ];
translate_to_cpp("reverse", _) ->
    [
        "    { auto lst = pop(s);\n",
        "      auto vec = lst.as_list();\n",
        "      std::reverse(vec.begin(), vec.end());\n",
        "      push(s, Value::make_list(vec)); }\n"
    ];
translate_to_cpp("append", _) ->
    [
        "    { auto a = pop(s); auto b = pop(s);\n",
        "      auto vec = b.as_list();\n",
        "      auto& avec = a.as_list();\n",
        "      vec.insert(vec.end(), avec.begin(), avec.end());\n",
        "      push(s, Value::make_list(vec)); }\n"
    ];

%% I/O
translate_to_cpp("print", _) ->
    [
        "    { auto a = pop(s);\n",
        "      switch (a.type) {\n",
        "          case Type::Int: std::cout << a.as_int(); break;\n",
        "          case Type::Float: std::cout << a.as_float(); break;\n",
        "          case Type::Bool: std::cout << (a.as_bool() ? \"true\" : \"false\"); break;\n",
        "          case Type::String: std::cout << a.as_string(); break;\n",
        "          case Type::Atom: std::cout << a.as_string(); break;\n",
        "          default: std::cout << \"<value>\"; break;\n",
        "      }\n",
        "      std::cout << '\\n'; }\n"
    ];
translate_to_cpp("stack", _) ->
    [
        "    if (s.empty()) { std::cout << \"Stack empty\\n\"; }\n",
        "    else {\n",
        "        std::cout << \"Stack(\" << s.size() << \"):\\n\";\n",
        "        for (size_t i = 0; i < s.size(); ++i) {\n",
        "            std::cout << \"  \" << i << \") \";\n",
        "            auto& v = s[s.size() - 1 - i];\n",
        "            switch (v.type) {\n",
        "                case Type::Int: std::cout << v.as_int() << \" : Int\"; break;\n",
        "                case Type::Bool: std::cout << (v.as_bool()?\"true\":\"false\") << \" : Bool\"; break;\n",
        "                case Type::String: std::cout << v.as_string() << \" : String\"; break;\n",
        "                default: std::cout << \"<value>\"; break;\n",
        "            }\n",
        "            std::cout << '\\n';\n",
        "        }\n",
        "    }\n"
    ];

%% Assertions
translate_to_cpp("assert", _) ->
    [
        "    { auto a = pop(s);\n",
        "      if (!a.as_bool()) throw std::runtime_error(\"Assertion failed\"); }\n"
    ];
translate_to_cpp("assert-eq", _) ->
    [
        "    { auto expected = pop(s); auto actual = pop(s);\n",
        "      if (!(expected == actual)) throw std::runtime_error(\"Assert-eq failed\"); }\n"
    ];

%% Product type field access — handled via runtime dispatch on type_name
%% This is a fallback; known product ops get specialized code in generate_body
translate_to_cpp(Name, WordName) ->
    %% Check if this is a self-recursive call
    case Name =:= WordName of
        true ->
            ["    ", cpp_function_name(Name), "(s);\n"];
        false ->
            %% Check if it's a known word or a product type operation
            case is_product_field_op(Name) of
                {getter, TypeName, FieldName} ->
                    ["    op_", string:lowercase(TypeName), "_", FieldName, "(s);\n"];
                {setter, TypeName, FieldName} ->
                    ["    op_", string:lowercase(TypeName), "_", FieldName, "_set(s);\n"];
                {constructor, ConstructorName} ->
                    ["    make_", ConstructorName, "_push(s);\n"];
                false ->
                    %% Try as a compiled word call
                    case af_word_compiler:find_compiled_word_defs(Name) of
                        [_ | _] ->
                            ["    ", cpp_function_name(Name), "(s);\n"];
                        [] ->
                            %% Literal or unknown — try int/bool literal
                            case try_literal(Name) of
                                {int, V} ->
                                    ["    push(s, Value::make_int(", integer_to_list(V), "));\n"];
                                {bool, true} ->
                                    "    push(s, Value::make_bool(true));\n";
                                {bool, false} ->
                                    "    push(s, Value::make_bool(false));\n";
                                {string, S} ->
                                    ["    push(s, Value::make_string(\"", escape_cpp_string(S), "\"));\n"];
                                not_found ->
                                    ["    // Unknown op: ", Name, "\n",
                                     "    push(s, Value::make_atom(\"", escape_cpp_string(Name), "\"));\n"]
                            end
                    end
            end
    end.

%%% ===================================================================
%%% Main Generation
%%% ===================================================================

generate_main(_ModName) ->
    [
        "} // namespace af\n\n",
        "#ifndef AF_NO_MAIN\n",
        "int main() {\n",
        "    af::Stack s;\n",
        "    // Call the last defined word or customize entry point here\n",
        "    return 0;\n",
        "}\n",
        "#endif\n"
    ].

%%% ===================================================================
%%% Helpers
%%% ===================================================================

%% Find all compiled word definitions from the type registry
find_all_compiled_words() ->
    AllTypes = af_type:all_types(),
    lists:flatmap(fun(#af_type{ops = Ops}) ->
        lists:flatmap(fun({_OpName, OpList}) ->
            lists:filtermap(fun(#operation{name = N, sig_in = SI, sig_out = SO,
                                          source = {compiled, Body}}) ->
                {true, {N, SI, SO, Body}};
            (_) -> false
            end, OpList)
        end, maps:to_list(Ops))
    end, AllTypes).

%% Find all product types (types with auto-generated ops)
find_all_product_types() ->
    AllTypes = af_type:all_types(),
    lists:filtermap(fun(#af_type{name = Name, ops = Ops}) ->
        %% Product types have ops with source = auto
        HasAuto = lists:any(fun({_OpName, OpList}) ->
            lists:any(fun(#operation{source = auto}) -> true; (_) -> false end, OpList)
        end, maps:to_list(Ops)),
        case HasAuto andalso Name =/= 'Any' of
            true ->
                %% Extract fields from the constructor's sig_in
                ConstructorName = string:lowercase(atom_to_list(Name)),
                case find_constructor_fields(ConstructorName, Ops, AllTypes) of
                    {ok, Fields} -> {true, {Name, Fields}};
                    not_found -> false
                end;
            false -> false
        end
    end, AllTypes).

%% Find constructor fields by looking at the constructor op in Any
find_constructor_fields(ConstructorName, _Ops, AllTypes) ->
    %% Constructor is registered in Any
    AnyOps = case lists:keyfind('Any', #af_type.name, AllTypes) of
        #af_type{ops = O} -> O;
        false -> #{}
    end,
    case maps:get(ConstructorName, AnyOps, []) of
        [#operation{sig_in = SigIn, sig_out = [TypeName], source = auto} | _] ->
            %% SigIn is reversed field types; reconstruct field names from getters
            FieldTypes = lists:reverse(SigIn),
            FieldNames = find_field_names(TypeName, AllTypes),
            case length(FieldTypes) =:= length(FieldNames) of
                true -> {ok, lists:zip(FieldNames, FieldTypes)};
                false -> not_found
            end;
        _ -> not_found
    end.

%% Find field names by looking at getter ops in the type's dict
find_field_names(TypeName, AllTypes) ->
    case lists:keyfind(TypeName, #af_type.name, AllTypes) of
        #af_type{ops = Ops} ->
            GetterNames = [list_to_atom(N) || {N, [#operation{source = auto, sig_out = [_, TypeName2]} | _]} <- maps:to_list(Ops),
                           TypeName2 =:= TypeName],
            lists:sort(GetterNames);
        false -> []
    end.

%% Check if a name is a product field operation
is_product_field_op(Name) ->
    AllTypes = af_type:all_types(),
    %% Check setters (name ends with !)
    case lists:suffix("!", Name) of
        true ->
            FieldName = lists:droplast(Name),
            find_setter_type(FieldName, AllTypes);
        false ->
            find_getter_type(Name, AllTypes)
    end.

find_getter_type(Name, AllTypes) ->
    Result = lists:filtermap(fun(#af_type{name = TypeName, ops = Ops}) ->
        case TypeName of
            'Any' -> false;
            'Atom' -> false;
            _ ->
                case maps:get(Name, Ops, []) of
                    [#operation{source = auto} | _] ->
                        {true, {getter, atom_to_list(TypeName), Name}};
                    _ -> false
                end
        end
    end, AllTypes),
    case Result of
        [Hit | _] -> Hit;
        [] -> false
    end.

find_setter_type(FieldName, AllTypes) ->
    SetterName = FieldName ++ "!",
    %% Setters are registered in Any
    case lists:keyfind('Any', #af_type.name, AllTypes) of
        #af_type{ops = Ops} ->
            case maps:get(SetterName, Ops, []) of
                [#operation{source = auto, sig_out = [TypeName]} | _] ->
                    {setter, atom_to_list(TypeName), FieldName};
                _ -> false
            end;
        false -> false
    end.

%% Group word defs by name
group_by_name(WordDefs) ->
    Groups = lists:foldl(fun({Name, _, _, _} = Def, Acc) ->
        Existing = maps:get(Name, Acc, []),
        maps:put(Name, Existing ++ [Def], Acc)
    end, #{}, WordDefs),
    maps:to_list(Groups).

%% Convert A4 word name to valid C++ identifier
cpp_function_name(Name) ->
    Mapped = lists:map(fun(C) ->
        case C of
            $- -> $_;
            $? -> $Q;
            $! -> $X;
            $< -> $L;
            $> -> $G;
            $+ -> $P;
            $* -> $M;
            $/ -> $D;
            $= -> $E;
            _ -> C
        end
    end, Name),
    %% Prefix with af_ if it's a C++ reserved word
    case is_cpp_reserved(Mapped) of
        true -> "af_" ++ Mapped;
        false -> Mapped
    end.

is_cpp_reserved(Name) ->
    lists:member(Name, [
        "double", "float", "int", "long", "short", "char", "bool",
        "void", "auto", "class", "struct", "enum", "union", "namespace",
        "if", "else", "for", "while", "do", "switch", "case", "break",
        "continue", "return", "goto", "default", "try", "catch", "throw",
        "new", "delete", "this", "true", "false", "const", "static",
        "extern", "inline", "virtual", "override", "final", "public",
        "private", "protected", "template", "typename", "using",
        "operator", "sizeof", "alignof", "decltype", "constexpr",
        "nullptr", "noexcept", "register", "volatile", "mutable"
    ]).

%% C++ parameter type from A4 type
cpp_param_type('Int') -> "int64_t";
cpp_param_type('Float') -> "double";
cpp_param_type('Bool') -> "bool";
cpp_param_type('String') -> "const std::string&";
cpp_param_type(_) -> "const Value&".

%% Make a Value from a C++ variable
cpp_make_value('Int', Var) -> ["Value::make_int(", Var, ")"];
cpp_make_value('Float', Var) -> ["Value::make_float(", Var, ")"];
cpp_make_value('Bool', Var) -> ["Value::make_bool(", Var, ")"];
cpp_make_value('String', Var) -> ["Value::make_string(", Var, ")"];
cpp_make_value(_, Var) -> Var.

%% Generate literal value for match conditions
cpp_literal_value('Int', V) when is_integer(V) ->
    ["Value::make_int(", integer_to_list(V), ")"];
cpp_literal_value('Bool', true) -> "Value::make_bool(true)";
cpp_literal_value('Bool', false) -> "Value::make_bool(false)";
cpp_literal_value('String', V) when is_list(V) ->
    ["Value::make_string(\"", escape_cpp_string(V), "\")"];
cpp_literal_value(Type, V) ->
    ["Value::make_atom(\"", io_lib:format("~p:~p", [Type, V]), "\")"].

%% Try to parse a token as a literal
try_literal(Name) ->
    case catch list_to_integer(Name) of
        V when is_integer(V) -> {int, V};
        _ ->
            case Name of
                "true" -> {bool, true};
                "false" -> {bool, false};
                _ -> not_found
            end
    end.

%% Format signature for comments
format_sig([]) -> "()";
format_sig(Sig) ->
    Items = [format_sig_item(S) || S <- lists:reverse(Sig)],
    lists:join(" ", Items).

format_sig_item({Type, Value}) ->
    io_lib:format("~p(~p)", [Type, Value]);
format_sig_item(Type) when is_atom(Type) ->
    atom_to_list(Type).

%% Escape string for C++ string literal
escape_cpp_string(S) ->
    lists:flatmap(fun(C) ->
        case C of
            $\\ -> "\\\\";
            $" -> "\\\"";
            $\n -> "\\n";
            $\t -> "\\t";
            _ -> [C]
        end
    end, S).
